# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm install create-nw-react-app -g --yes
      - run: npm install
      - run: npm run build --if-present
      - name: Upload win64 Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: win64
          path: ${{ github.workspace }}/build/eldron/win64
      - name: Upload osx64 Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: osx64
          path: ${{ github.workspace }}/build/eldron/osx64
